### ISSUE TITLE
Trouble importing FaceONNX detector model: `Only tensor indices is valid`

### ISSUE THREAD

**Issue by SimonBrandner** [tracel-ai/burn#1915] opened 2024-06-21 10:24 UTC
**Describe the bug**

Error during importing the detector model: 

```
ERROR burn_import::logger: PANIC => panicked at /home/simon/Data1/GIT/Rust/burn/crates/burn-import/src/onnx/dim_inference.rs:820:14:
Only tensor indices is valid    
```

**To Reproduce**
1. Download detector model from https://drive.google.com/file/d/1tB7Y5l5Jf2270IisgSZ3rbCQs0-pkNIQ/view?usp=drive_link (also attached down below)
2. Move the file to `src/model/detector.onnx`
3. Add this to `build.rs`

```rs
	ModelGen::new()
		.input("src/model/detector.onnx")
		.out_dir("model/")
		.run_from_script();

```

4. Build and see error

**What I've figured out so far**

- There is something going on when updating the gather outputs: https://github.com/tracel-ai/burn/blob/main/crates/burn-import/src/onnx/dim_inference.rs#L812

Attachment:
[face_detector_640.onnx.zip](https://github.com/user-attachments/files/16045435/face_detector_640.onnx.zip)

**Comment by laggui** [comment] 2024-06-21 11:45
As you correctly pointed out the issue is with the gather node.

We check for the inputs to make sure they are in accordance with the spec, but when checking for the indices we expect a tensor but your model uses a scalar (rank 0 tensor) - which is still valid.

I'll open a PR to fix that.

**Comment by laggui** [comment] 2024-06-21 12:29
Also I just realized your model was generated with an older opset (v9) and we might not support all of the ops there. Right now the ops we have should support the latest ops at opset 13. Some also have support for older opset but not all (e.g., `Slice` which I see in your model is opset v1 and we don't parse the attributes).

The ONNX spec is large and our bandwidth for that is a bit limited.

**Comment by antimora** [comment] 2024-06-30 16:51
We should probably fix this to support older opset. 

As a work around, can you convert to a new opset? There are some tools to upgrade the onnx file.

**Comment by SimonBrandner** [comment] 2024-07-01 08:19
I tried [this](https://github.com/openppl-public/ppl.nn/blob/master/docs/en/onnx-model-opset-convert-guide.md) and it did not help... That said from the comments my understanding is that the `Only tensor indices is valid` issue isn't due to an old opset, is it?

**Comment by SimonBrandner** [comment] 2024-07-01 09:04
This dirty fix seems to be working:

```diff
diff --git a/crates/burn-import/src/onnx/dim_inference.rs b/crates/burn-import/src/onnx/dim_inference.rs
index 94d66d22..c404829c 100644
--- a/crates/burn-import/src/onnx/dim_inference.rs
+++ b/crates/burn-import/src/onnx/dim_inference.rs
@@ -808,11 +808,16 @@ fn gather_update_outputs(node: &mut Node) {
     };
 
     let indices_tensor = match &node.inputs[1].ty {
-        ArgType::Tensor(tensor) => tensor,
-        _ => panic!("Only tensor indices is valid"),
+        ArgType::Tensor(tensor) => tensor.clone(),
+        ArgType::Scalar(scalar) => TensorType {
+            elem_type: scalar.clone(),
+            dim: 0,
+            shape: None,
+        },
+        _ => panic!("Only tensor or scalar indices are valid"),
     };
 
-    if indices_tensor.dim != 1 {
+    if indices_tensor.dim > 1 {
         panic!("Gather: indices tensor rank above 1 not supported")
     } 
```

but then I run into this:

```
ERROR burn_import::logger: PANIC => panicked at /home/simon/GIT/Rust/burn/crates/burn-import/src/onnx/op_configuration.rs:302:9:
Flatten: input tensor must have at least 2 dimensions (got 0)    
```

(btw, is there a Discord server/Matrix space/whatever which would be more suitable for debugging this?)

**Comment by SimonBrandner** [comment] 2024-07-01 09:07
As far as I can tell, according to the docs, the input tensor really must hast at least 2 dimensions which makes me ask how is it I am getting a 0D one...

https://onnx.ai/onnx/operators/onnx__Flatten.html

**Comment by laggui** [comment] 2024-07-02 12:07
> (btw, is there a Discord server/Matrix space/whatever which would be more suitable for debugging this?)

Absolutely! Come join us [here](https://discord.gg/uPEBbYYDB6).

**Comment by laggui** [comment] 2024-07-02 12:17
> I tried [this](https://github.com/openppl-public/ppl.nn/blob/master/docs/en/onnx-model-opset-convert-guide.md) and it did not help... That said from the comments my understanding is that the `Only tensor indices is valid` issue isn't due to an old opset, is it?

Yeah it's not *just* because of the opset. Right now the first errors you're seeing are due to the rank 0 tensor. When I checked your model last time the gather node used a single value to gather and then it was unsqueezed to a 1-dim tensor.

We currently don't support 0-dim tensors, so even if we try to work around it by returning a 1d tensor I don't think the rest of the codegen will match. We would have to add support for that.

Finally, you do have some ops that use an older opset which may not be supported (as pointed out in my last comment, some attributes which don't exist in new opsets are not parsed).

**Comment by antimora** [comment] 2024-07-07 02:24
This part needs to be fixed: <img width="463" alt="image" src="https://github.com/tracel-ai/burn/assets/939125/b38b0c83-045d-4433-94fd-bd79c0527adb">

We need to support Gather, Unsqueeze, and Concat operations on Shape

**Comment by antimora** [comment] 2024-07-07 03:52
Used `onnx-simplifier` (https://github.com/daquexian/onnx-simplifier) which removes lots of these crazy gather reshape operation, which were due to lacking capabilities of the older ONNX OpSet versions. 

Here is updated version:

[face_detector_opt.onnx.zip](https://github.com/user-attachments/files/16118060/face_detector_opt.onnx.zip)

Output of the tool:
```
[burn]% onnxsim ~/Downloads/face_detector_640.onnx ./face_detector_opt.onnx
Simplifying...
Finish! Here is the difference:
┏━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┓
┃                    ┃ Original Model ┃ Simplified Model ┃
┡━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━┩
│ Add                │ 3              │ 3                │
│ BatchNormalization │ 35             │ 0                │
│ Concat             │ 13             │ 5                │
│ Constant           │ 240            │ 111              │
│ Conv               │ 52             │ 52               │
│ Div                │ 2              │ 1                │
│ Exp                │ 1              │ 1                │
│ Gather             │ 8              │ 0                │
│ Mul                │ 4              │ 4                │
│ Relu               │ 37             │ 37               │
│ Reshape            │ 8              │ 8                │
│ Shape              │ 8              │ 0                │
│ Slice              │ 6              │ 4                │
│ Softmax            │ 1              │ 1                │
│ Sub                │ 1              │ 1                │
│ Transpose          │ 8              │ 8                │
│ Unsqueeze          │ 24             │ 0                │
│ Model Size         │ 1.5MiB         │ 1.3MiB           │
└────────────────────┴────────────────┴──────────────────┘
```

Now, there is still a slight issue with Slice operation which does not support attributes. I am working on this fix. 

<img width="506" alt="image" src="https://github.com/tracel-ai/burn/assets/939125/aa9f61fd-6977-4e73-85c3-0d9aa33ffec3">

**Comment by laggui** [comment] 2024-07-07 17:23
> Used `onnx-simplifier` (https://github.com/daquexian/onnx-simplifier) which removes lots of these crazy gather reshape operation, which were due to lacking capabilities of the older ONNX OpSet versions.
> 
> Here is updated version:
> 
> [face_detector_opt.onnx.zip](https://github.com/user-attachments/files/16118060/face_detector_opt.onnx.zip)
> 
> Output of the tool:
> 
> ```
> [burn]% onnxsim ~/Downloads/face_detector_640.onnx ./face_detector_opt.onnx
> Simplifying...
> Finish! Here is the difference:
> ┏━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┓
> ┃                    ┃ Original Model ┃ Simplified Model ┃
> ┡━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━┩
> │ Add                │ 3              │ 3                │
> │ BatchNormalization │ 35             │ 0                │
> │ Concat             │ 13             │ 5                │
> │ Constant           │ 240            │ 111              │
> │ Conv               │ 52             │ 52               │
> │ Div                │ 2              │ 1                │
> │ Exp                │ 1              │ 1                │
> │ Gather             │ 8              │ 0                │
> │ Mul                │ 4              │ 4                │
> │ Relu               │ 37             │ 37               │
> │ Reshape            │ 8              │ 8                │
> │ Shape              │ 8              │ 0                │
> │ Slice              │ 6              │ 4                │
> │ Softmax            │ 1              │ 1                │
> │ Sub                │ 1              │ 1                │
> │ Transpose          │ 8              │ 8                │
> │ Unsqueeze          │ 24             │ 0                │
> │ Model Size         │ 1.5MiB         │ 1.3MiB           │
> └────────────────────┴────────────────┴──────────────────┘
> ```
> 
> Now, there is still a slight issue with Slice operation which does not support attributes. I am working on this fix.
> <img alt="image" width="506" src="https://private-user-images.githubusercontent.com/939125/346310222-aa9f61fd-6977-4e73-85c3-0d9aa33ffec3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNzMyODgsIm5iZiI6MTcyMDM3Mjk4OCwicGF0aCI6Ii85MzkxMjUvMzQ2MzEwMjIyLWFhOWY2MWZkLTY5NzctNGU3My04NWMzLTBkOWFhMzNmZmVjMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzA3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcwN1QxNzIzMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wY2M2NDEyZTNjMTc3ZDNhNTFjNTFkNzJlZTc3MzI2ODg0ZmY1MDdjNDJhYjgwZWMwMjUzMDhjNjJiOGQyYzQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Bhqs8LTmBrTn4rBPlsHEp9raTFxgpLwDw5WszB2hwC0">

Ha, that's what I suggested on discord. Glad it cleared up the redundant stuff 🙂

**Comment by antimora** [comment] 2024-07-08 03:55
Submitted a PR for the slice issue: https://github.com/tracel-ai/burn/pull/1989

But I stumbled another bug: https://github.com/tracel-ai/burn/issues/1983 which I am working to fix. 

Overall, I think I am very close to fixing it. The good news is that all ops seems to be working.

**Comment by antimora** [comment] 2024-07-19 22:10
I got the face-onnx building, however, there is a run-time error that's probably introduced recently when we were refactoring tensors. @laggui did some work in the Tensor random initialization. Maybe he knows what's going on. 

I am attaching all my artifacts here in my repository, which will be hosted temporarily: 

https://github.com/antimora/face-onnx

Please continue debugging. I think the bug is in the Burn's core.

**Comment by antimora** [comment] 2024-07-20 04:35
> I got the face-onnx building, however, there is a run-time error that's probably introduced recently when we were refactoring tensors. @laggui did some work in the Tensor random initialization. Maybe he knows what's going on.
> 
> I am attaching all my artifacts here in my repository, which will be hosted temporarily:
> 
> https://github.com/antimora/face-onnx
> 
> Please continue debugging. I think the bug is in the Burn's core.

I have filed the model initialization bugs here: https://github.com/tracel-ai/burn/issues/2043

**Comment by antimora** [comment] 2024-07-23 16:38
@SimonBrandner has confirmed the transformed ONNX file works now. 

This issue can be closed after #2008 is merged.

**Comment by laggui** [comment] 2024-08-08 13:15
Just a note that while the original issue was circumvented with the help of onnx-simplifier, it does not always appear to remove the problematic gather node with indices being a scalar.

Another discord user faced the same issue, and onnx-simplifier did not change the gather op. In this case the node is not followed by an unsqueeze operation.

![Gather node](https://github.com/user-attachments/assets/e8a42745-805f-4536-8d7f-688550a3516f)

So for `indices` being a single scalar, we have two blockers:

1. there is no 0-dim tensor (scalar) support in Burn
2. the gather op with a scalar index removes a dimension, and there is no matching operation that performs this in Burn right now. We would need to do a sequence of `tensor.select(dim, indices).squeeze(dim)` (provided that the scalar is instead provided as `[scalar]` to make it 1d)

**Comment by antimora** [comment] 2024-10-29 17:37
@laggui I have unassigned myself from this issue. As I recall, @SimonBrandner has linked an older version. So people who asked our help with FaceONNX is probably for newer versions. 

I am closing it for now.

**Closed by antimora** 2024-10-29 17:37 UTC
Labels: bug, onnx
