### ISSUE TITLE
Heap memory leak from `AutodiffTensor`

### ISSUE THREAD

**Issue by AsherJingkongChen** [tracel-ai/burn#2333] opened 2024-10-03 15:39 UTC
**Describe the bug**

The memory leaks come from `AutodiffTensor`. They only appear in the case:
1. The backend is `Autodiff<B>` (AD-enabled).
2. The model/param/tensor requires grad (Tracked).

I profile a simple example using Apple's Instruments.app (v15.3), and I find memory leaks.

**To Reproduce**

I opened a [repository](https://github.com/AsherJingkongChen/burn-model-linear) as an example of memory leaks. It trains a simple linear model. Without Apple's Instruments.app, you can find memory leaks using [Valgrind](https://valgrind.org).

You can clone the example git repository here: https://github.com/AsherJingkongChen/burn-model-linear.git

**Expected behavior**

I expect no memory leak comes from any tracked `AutodiffTensor`.

**Screenshots**

* `leak.1.trace.png`: There are 5100 persistent allocations from `AutodiffTensor::new` in about 2000 iterations.

    ![leak.1.trace.png, Debug build, macOS ARM64, Instruments.app v15.3](https://github.com/AsherJingkongChen/burn-model-linear/blob/main/doc/img/leak.1.trace.png?raw=true)

**Desktop**

 - OS: macOS
 - Arch: ARM64
 - Version: 14.6.1

**Additional context**

I think there are some circular references of `rc: Arc<NodeId>` after the step is tracked. Sadly, it is too hard to locate the bug. I need tools to show me where circular references are.

The leak problem would be severe when I frequently replace the autodiff tensors or train a large model in hours. 🥺

**Comment by laggui** [comment] 2024-10-07 15:52
Thanks for flagging this and linking the MWE 🙏 

I reproduced the issue with your MWE as well as another training example - looks like some nodes are not removed from the graph hashmap.

The capacity increases pretty slowly over time as you've noticed. So while not super critical, still not great 😅

**Comment by AsherJingkongChen** [comment] 2024-10-07 16:10
> Thanks for flagging this and linking the MWE 🙏 
> 
> I reproduced the issue with your MWE as well as another training example - looks like some nodes are not removed from the graph hashmap.
> 
> The capacity increases pretty slowly over time as you've noticed. So while not super critical, still not great 😅 

Thank you for spotting the problem out. I am still thinking solutions. I think checking the nodes in the graph would help.

It would be severe only in some cases, especially frequently updating/replacing parameters. Actually, I found this because my program caused 30GB swaps.

**Comment by AsherJingkongChen** [comment] 2024-10-07 17:29
## The example (MWE) has new branch [`wgpu/eager`](https://github.com/AsherJingkongChen/burn-model-linear)

**Description**

* Wgpu backend
* Faster growth of persistent memory size

**Screenshots**

* In Apple's Instruments.app, I can see an allocation slope `(90 MB -> 120 MB)`:
    
     <img width="344" alt="image" src="https://github.com/user-attachments/assets/aa90f9a0-3836-454a-8add-aae4eaeb2309">

**Comment by laggui** [comment] 2024-10-07 18:16
Was going to investigate this one but I stumbled upon this possibly linked issue #2042.

I think these are two separate issues you're observing with your new branch, though both of these should be fixed.

I'm working on something right now but I'll have to prioritize these as soon as I can.

**Comment by AsherJingkongChen** [comment] 2024-10-07 21:58
# Added branch [`bench/heap-leak`](https://github.com/AsherJingkongChen/burn-model-linear/tree/bench/heap-leak) at example

## Description

To see which backend setting has leaks and trace their heap profiles.

## Result

I take snapshots every 10 seconds for 1 minute using Apple's `Instruments.app`

| Binary Name | Leaks on debug | Leaks on release |
| `ndarray-ad-false` | `0` | `0` |
| `ndarray-ad-true` | `13233` | `13439` |
| `wgpu-ad-false` | `59810` | `30131` |
| `wgpu-ad-true` | `21141` | `13487` |

*-ad- refers to autodiff feature*

**Comment by AsherJingkongChen** [comment] 2024-10-07 23:26
## Question

Will #1962 be recognized as a heap memory leak?

**Closed** 2024-10-09 12:53 UTC
Labels: bug
